FROM ubuntu:14.04

RUN rm -rf /var/lib/apt/lists/* && apt-get clean && apt-get update && apt-get install -y build-essential python2.7 python2.7-dev python-pip python-virtualenv && rm -rf /var/lib/apt/lists/* && apt-get clean

EXPOSE 8080

WORKDIR /solution

CMD ["make", "install", "go"]

